export const notifications = [
  {
    id: 1,
    title: "Tạm ngưng tuyến US-DPP",
    user: "Tâm",
    time: "12-07-2025",
    type: "warning",
    isRead: false,
    locked: false,
    iconName: "alert-triangle",
  },
  {
    id: 2,
    title: "Lịch bay DHL-Tuyến EU...",
    user: "Tâm",
    time: "12-07-2025",
    type: "info",
    isRead: true,
    locked: true,
    iconName: "calendar",
  },
  {
    id: 3,
    title: "Tạm ngưng tuyến US-DPP",
    user: "Tâm",
    time: "12-07-2025",
    type: "warning",
    isRead: false,
    locked: false,
    iconName: "alert-triangle",
  },
  {
    id: 4,
    title: "Lịch bay DHL-Tuyến EU...",
    user: "Tâm",
    time: "12-07-2025",
    type: "info",
    isRead: true,
    locked: true,
    iconName: "calendar",
  },
];
