export const countryServices = [
  {
    flag: "🇦🇺",
    name: "Australia",
    avatarUrl: "https://randomuser.me/api/portraits/men/20.jpg",
    services: [
      {
        name: "Cơ guyên, tuyến",
        badge: "64 đơn hàng",
        badgeColor: "blue",
        orders: 64,
        days: 5,
        grossW: "196.2 Kg",
        chargedW: "972 KG",
        reWeight: "292 kg",
        revenue: "$478,981,234",
        profit: "42,231,221",
        tisuat: "67%",
        tigiao: "100%",
      },
      {
        name: "AUS chuyên tuyến",
        badge: "64 đơn hàng",
        badgeColor: "blue",
        orders: 64,
        days: 5,
        grossW: "196.2 Kg",
        chargedW: "284 Kg",
        reWeight: "292 kg",
        revenue: "122,374,192đ",
        profit: "42,231,221",
        avatarUrl: "https://randomuser.me/api/portraits/men/10.jpg",
      },
      {
        name: "UPS 8 BD",
        badge: "45 đơn hàng",
        badgeColor: "blue",
        orders: 45,
        days: 5,
        grossW: "1,214.7 kg",
        chargedW: "1,581 Kg",
        reWeight: "1,321 kg",
        revenue: "351,607,344đ",
        profit: "72,231,221",
        avatarUrl: "https://randomuser.me/api/portraits/men/11.jpg",
      },
    ],
  },
  {
    flag: "🇺🇸",
    name: "United S..",
    avatarUrl: "https://randomuser.me/api/portraits/men/21.jpg",
    services: [
      {
        name: "UPS 8 BD",
        badge: "64 đơn hàng",
        badgeColor: "blue",
        orders: 64,
        days: 4,
        grossW: "196.2 Kg",
        chargedW: "972 KG",
        reWeight: "292 kg",
        revenue: "$478,981,234",
        profit: "42,231,221",
        tisuat: "67%",
        tigiao: "97%",
      },
      {
        name: "FedEx Priority",
        badge: "38 đơn hàng",
        badgeColor: "blue",
        orders: 38,
        days: 5,
        grossW: "756.2 kg",
        chargedW: "892 Kg",
        reWeight: "892 kg",
        revenue: "198,450,000đ",
        profit: "38,550,000",
        avatarUrl: "https://randomuser.me/api/portraits/men/12.jpg",
      },
    ],
  },
  {
    flag: "🇰🇷",
    name: "Korean",
    avatarUrl: "https://randomuser.me/api/portraits/men/22.jpg",
    services: [
      {
        name: "Dịch vụ",
        badge: "64 đơn hàng",
        badgeColor: "blue",
        orders: 64,
        days: 6,
        grossW: "196.2 Kg",
        chargedW: "972 KG",
        reWeight: "292 kg",
        revenue: "$478,981,234",
        profit: "42,231,221",
        tisuat: "67%",
        tigiao: "99%",
      },
      {
        name: "EMS Standard",
        badge: "28 đơn hàng",
        badgeColor: "blue",
        orders: 28,
        days: 7,
        grossW: "532.8 kg",
        chargedW: "615 Kg",
        reWeight: "615 kg",
        revenue: "145,320,000đ",
        profit: "28,640,000",
        avatarUrl: "https://randomuser.me/api/portraits/men/13.jpg",
      },
    ],
  },
  {
    flag: "🇹🇼",
    name: "Taiwan",
    avatarUrl: "https://randomuser.me/api/portraits/women/10.jpg",
    services: [
      {
        name: "Dịch vụ",
        badge: "64 đơn hàng",
        badgeColor: "blue",
        orders: 64,
        days: 8,
        grossW: "196.2 Kg",
        chargedW: "972 KG",
        reWeight: "292 kg",
        revenue: "$478,981,234",
        profit: "42,231,221",
        tisuat: "67%",
        tigiao: "80%",
      },
      {
        name: "China Post",
        badge: "22 đơn hàng",
        badgeColor: "blue",
        orders: 22,
        days: 9,
        grossW: "428.5 kg",
        chargedW: "505 Kg",
        reWeight: "505 kg",
        revenue: "98,750,000đ",
        profit: "18,450,000",
        avatarUrl: "https://randomuser.me/api/portraits/women/3.jpg",
      },
    ],
  },
];
