export const userStats = [
  {
    name: "Cường",
    code: "SVIP01",
    orders: 24,
    weight: 135,
    totalWeight: 154,
    revenue: 122283000,
    avatarUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    color: "blue",
    topIndex: 1,
  },
  {
    name: "Long",
    code: "SVIP02",
    orders: 18,
    weight: 135,
    totalWeight: 154,
    revenue: 99990000,
    avatarUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    color: "orange",
    topIndex: 2,
  },
  {
    name: "Xuân",
    code: "STV24",
    orders: 14,
    weight: 78,
    totalWeight: 78,
    revenue: 73432100,
    avatarUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    color: "rose",
    topIndex: 3,
  },
  {
    name: "Dương",
    code: "VIP51",
    orders: 8,
    weight: 68,
    totalWeight: 88,
    revenue: 38793900,
    avatarUrl: "https://randomuser.me/api/portraits/men/4.jpg",
    color: "emerald",
    topIndex: null,
  },
  {
    name: "Việt",
    code: "LT145",
    orders: 4,
    weight: 54,
    totalWeight: 57,
    revenue: 23251000,
    avatarUrl: "https://randomuser.me/api/portraits/men/5.jpg",
    color: "slate",
    topIndex: null,
  },
  {
    name: "Sương",
    code: "S7N03",
    orders: 2,
    weight: 25,
    totalWeight: 28,
    revenue: 17331000,
    avatarUrl: "https://randomuser.me/api/portraits/women/1.jpg",
    color: "slate",
    topIndex: null,
  },
  {
    name: "Phong",
    code: "STN12",
    orders: 0,
    weight: 0,
    totalWeight: 0,
    revenue: 0,
    avatarUrl: "https://randomuser.me/api/portraits/men/5.jpg",
    color: "slate",
    topIndex: null,
  },
];
