import { Scale, Percent, Receipt, DollarSign } from "lucide-react";

export const statsData = {
  weight: {
    title: "CÂN NẶNG",
    value: "675",
    unit: "Kg",
    valueSub: "723 Kg",
    percent: "+2,01%",
    percentColor: "text-green-600",
    borderColor: "border-lime-400",
    bg: "bg-lime-50",
    textColor: "text-slate-900",
    icon: <Scale className="w-6 h-6 text-lime-400" />,
    percentOnBottom: false,
  },
  saleCommission: {
    title: "HOA HỒNG SALE",
    value: "$11,208,400",
    unit: "đ",
    percent: "25,2%",
    percentColor: "text-red-500",
    borderColor: "border-rose-400",
    bg: "bg-rose-50",
    textColor: "text-slate-900",
    icon: <Percent className="w-6 h-6 text-rose-400" />,
    percentOnBottom: true,
  },
  totalTax: {
    title: "TỔNG THUẾ",
    value: "$14,131,580",
    unit: "đ",
    percent: "8,02%",
    percentColor: "text-orange-500",
    borderColor: "border-amber-400",
    bg: "bg-amber-50",
    textColor: "text-slate-900",
    icon: <Receipt className="w-6 h-6 text-amber-400" />,
    percentOnBottom: true,
  },
  profit: {
    title: "LỢI NHUẬN",
    value: "$46,278,620",
    unit: "đ",
    percent: "32,02%",
    percentColor: "text-green-600",
    borderColor: "border-emerald-400",
    bg: "bg-emerald-50",
    textColor: "text-slate-900",
    icon: <DollarSign className="w-6 h-6 text-emerald-400" />,
    percentOnBottom: true,
  },
};
